// Custom Worker entry point. Re-uses the fetch handler generated by OpenNext
// and adds a scheduled handler that polls active RSS/Atom feeds for the
// rewrite-and-review pipeline. See:
// https://opennext.js.org/cloudflare/howtos/custom-worker
//
// @ts-expect-error `.open-next/worker.ts` is generated at build time
import { default as handler } from "./.open-next/worker.js";

import type { ExportedHandler } from "@cloudflare/workers-types";

import { ingestAllFeeds } from "@/lib/server/feeds/pipeline";

export default {
  fetch: handler.fetch,

  async scheduled(event, env) {
    try {
      const summary = await ingestAllFeeds(env.DB);
      console.log(
        `[pressready] feed ingestion: ${summary.totalParsed} items parsed, ` +
          `${summary.totalAdded} added, ${summary.failedCount} feeds failed.`,
      );
    } catch (error) {
      console.error("[pressready] feed ingestion failed", error);
    }
  },
} satisfies ExportedHandler<CloudflareEnv>;
